### ISSUE TITLE
Add functionality for specific file names for each languaje

### ISSUE THREAD

**Issue by Dunos** [webyom/gulp-html-i18n#10]
Hey, it would be really awesome if we could have the functionality to have different files names for each languaje, maybe having another JSON like routes.json or something, so in the end we have a tree like the following:

**build**
└── **en**
          ── home.html
└── **es**
          ── inicio.html

Great job with this plugin anyway :)

**Comment by webyom** [comment]
@Dunos please upgrade to 0.3.4 and refer to `filenameI18n` option

**Comment by Dunos** [comment]
It works like a charm, many thanks! :D

**Comment by webyom** [comment]
@boldhaus thanks for your feedback. I have fixed this issue, please update to `0.4.2`.
