### ISSUE TITLE
Option to maintain file extensions to use with non HTML files

### ISSUE THREAD

**Issue by Dunos** [webyom/gulp-html-i18n#11]
Hi there again!

I know this gulp module is supposed to be used with HTML files, but I think it would be great to add the option of another parameter in the config to maintain the original extension of the translated files instead always adding the .html (this tool already accepts non HTML files and translate them perfectly but always renames them after).

Thanks in advance :)

**Comment by webyom** [comment]
@Dunos please upgrade to `0.4.0`, no option is needed.

**Comment by Dunos** [comment]
Works like a charm, many thanks again! :D
