### ISSUE TITLE
Update the documentation with missing options

### ISSUE THREAD

**Issue by neovov** [webyom/gulp-html-i18n#12]
Hi,

First of all, thanks for the plugin, it is really useful.

Could you, please, update the documentation by add the "escapeQuotes" and "langRegExp" options?
(I checked the source code to find those ; I was looking for the "langRegExp" one)

Thanks, keep up the good work 🍻!

**Comment by webyom** [comment]
@neovov thanks for you kindly reminder. I have updated the readme file accordingly.
