### ISSUE TITLE
Error: File can't be null

### ISSUE THREAD

**Issue by boldhaus** [webyom/gulp-html-i18n#14]
Dear @webyom, 

could you please have a look at the attached project [i18n.zip](https://github.com/webyom/gulp-html-i18n/files/304876/i18n.zip)?

Whenever there is a subdirectory (either empty or not) under the source directory I get the following error message:

```console
/gulp-i18n/node_modules/q/q.js:155

                throw e;
                ^
Error: File can't be null
```

The gulp task "test1" in the attached project works, while the tasks "test2" and "test3" produce the described error.

Thanks for having a look into this issue.

**Comment by webyom** [comment]
@boldhaus you should specify the extension name of the file in src, or else the folders will be passed for processing, which is considered null file.

**Comment by boldhaus** [comment]
@webyom 

Thanks for the information. It now works.
