### ISSUE TITLE
Localization of directory names

### ISSUE THREAD

**Issue by boldhaus** [webyom/gulp-html-i18n#15]
Dear @webyom ,

I do have a feature request. Maybe you also like the idea of localizing directory names.

Suppose you have the following project structure:

```
src
└── pages
  └── contact
    └── ${{contact.filename}}$.html
  └── ${{index.filename}}$.html
```

It would be nice if the possibility exists to localize the directory name (e.g. option directoryNameI18n) as well.

Then   

```
src
└── pages
  └── ${{contact.directoryName}}$
    └── ${{contact.filename}}$.html
  └── ${{index.filename}}$.html
```

would compile to

```
dist
└── kontakt
  └── kontakt.html
└── contact
  └── contact.html
└── index.html
```

What do you think about this idea?

**Comment by webyom** [comment]
@boldhaus actually it works for directory names, please have a try.

**Comment by boldhaus** [comment]
@webyom 

Thanks for the information. It works.
