### ISSUE TITLE
Ignores localised attributes

### ISSUE THREAD

**Issue by tempywritescode** [webyom/gulp-html-i18n#16]
You can't put localisation placeholders into element attributes. I know this is a potentially hacky usecase but I still think it would be useful. One use would be to change image src's depending on the language. Another is so I could turn this: <html lang="${{ _lang_ }}"> into <html lang="en">, or changing the contents of meta tags. Cheers!

**Comment by webyom** [comment]
@tempywritescode do you want to use it like this `<img src="./${{_lang_}}$/thumb.png" />`? Please have a try, it should work.

**Comment by tempywritescode** [comment]
That approach does work for images, but won't work for meta tags - for example in the description metatag you would want to swap out different strings in the "content" attribute. Thanks for your input!

**Comment by dominicscimeca** [comment]
I am not seeing this issue @tempywritescode. Can you post an example to test against. This plugin seems to work irregardless of location in the file or every filetype.

**Comment by dominicscimeca** [comment]
I submit this should be closed
