### ISSUE TITLE
'createLangDirs=true' not working as expected

### ISSUE THREAD

**Issue by andreas-henning** [webyom/gulp-html-i18n#20]
The plugin doesn't create the language directory correctly. In my environment, the plugin deals with origin file paths  similar to this:

`originPath: "c:\company-website\company\src\pages\index.html"`

when generating the german language page and when createLangDirs is set to true, the new file path is set to the following:

`newFilePath: "c:\company-website\company\src\pagesde\index.html"`

The separator between 'pages' and 'de' is missing. Modifying line 280 in index.coffee from:

`newFilePath = file.base + lang + '/' + newFilePath.slice(file.base.length)`

to:

`newFilePath = file.base + '/' + lang + newFilePath.slice(file.base.length)`

corrects the problem.

**Comment by dominicscimeca** [comment]
Could you please post your gulp task? or folder setup schema etc? to give more information. the creating lang dir works in some situations for sure. But we are seeing now that it doesn't work in others. so we would need to see what is the situation that it is not working for you. to make sure it continues to work for everyone. Thanks :)

**Comment by andreas-henning** [comment]
Sure!

My project is based on Zurb's [Foundation 6](http://foundation.zurb.com/sites.html) for Sites. I'm using the standard foundation-cli setup, so my entire directory structure and build environment is easily reproduced with npm. Make the project's parent directory the current directory and then do:

> npm install -g foundation-cli
> foundation new

I've made no changes to the directory structure this creates or to the generated build scripts other than what was necessary to incorporate i18n.

Excerpt from gulpfile.js
```
import i18n     from 'gulp-html-i18n';

<snipped>

// Copy page templates into finished HTML files
function pages() {
  return gulp.src('src/pages/**/*.{html,hbs,handlebars}')
    .pipe(panini({
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      data: 'src/data/',
      helpers: 'src/helpers/'
    }))
    .pipe(i18n({
      langDir: 'src/languages',
      delimiters: ['{${', '}$}'],
      createLangDirs: true,
      trace: true
    }))
    .pipe(gulp.dest(PATHS.dist));
}
```

Directory structure:
```
company
├──bower_components
├──dist
   ├──assets
   ├──de
   ├──en
├──etc
├──node_modules
├──src
   ├──assets
   ├──data
   ├──languages
   ├──layouts
   ├──pages
   ├──partials
   ├──styleguide
```
Note that the above structure is what I get after making the modification mentioned in my post. Without that modification what I get is this:

```
company
├──bower_components
├──dist
   ├──assets
├──etc
├──node_modules
├──pagesen        <-- oops
├──pagesde        <-- oops
├──src
   ├──assets
   ├──data
   ├──languages
   ├──layouts
   ├──pages
   ├──partials
   ├──styleguide
```

**Comment by dominicscimeca** [comment]
I just created a sample project. On windows 7. Using foundation, panini, and this plugin. And successfully created the directories. Are there more things to the operation? What is PATHS.dist?
Any more information would be helpful.

Also you can try using https://github.com/rvagg/through2 to check the base and path of the file names before and after i18n. and send that to give more information.

Here is the gulp task i used.
`gulp.task('pages',function(){
  return gulp.src('pages/**/*.html')
    .pipe(panini({
      root: 'pages/',
      layouts: 'layouts/',
      partials: 'partials/'
    }))
    .pipe(through2.obj(function (file, enc, callback) {
      console.log('before path',file.path);
      console.log('before base',file.base);

      callback(null, file)
    }))
    .pipe(i18n({
      langDir: 'languages',
      delimiters: ['{${', '}$}'],
      createLangDirs: true,
      trace: true
    }))
    .pipe(through2.obj(function (file, enc, callback) {
      console.log('after path',file.path);
      console.log('after base',file.base);

      callback(null, file)
    }))
    .pipe(gulp.dest('dist'));
})`

**Comment by andreas-henning** [comment]
Hmm. Strange.

PATHS.dist must be the same in both our installations:

`PATHS.dist: "dist"`

I can see from your gulpfile that we're not using the exact same setup. Look at the pipe to panini:

yours:
```
.pipe(panini({
      root: 'pages/',
      layouts: 'layouts/',
      partials: 'partials/'
    }))
```

mine:
```
.pipe(panini({
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      data: 'src/data/',
      helpers: 'src/helpers/'
    }))
```

After typing `foundation new`, did you setup the project using the following options:

```
A website (Foundation for Sites)
ZURB Template
```

That will give you the same gulpfile I'm using.  I know it shouldn't make a difference but it wouldn't hurt to use the exact same setup.

Anyway, this is what I get from through2 after adding your code to my gulpfile:
```
[11:37:32] Requiring external module babel-register
[11:37:36] Using gulpfile C:\Coalesense-Website\Coalesense\gulpfile.babel.js
[11:37:36] Starting 'default'...
[11:37:36] Starting 'build'...
[11:37:36] Starting 'clean'...
[11:37:36] Finished 'clean' after 17 ms
[11:37:36] Starting 'pages'...
[11:37:36] Starting 'sass'...
[11:37:36] Starting 'javascript'...
[11:37:36] Starting 'images'...
[11:37:36] Starting 'copy'...
before path C:\Coalesense-Website\Coalesense\src\pages\index.html
before base C:\Coalesense-Website\Coalesense\src\pages
after path C:\Coalesense-Website\Coalesense\src\pagesde/\index.html
after base C:\Coalesense-Website\Coalesense\src\pages
after path C:\Coalesense-Website\Coalesense\src\pagesen/\index.html
after base C:\Coalesense-Website\Coalesense\src\pages
[11:37:41] Finished 'sass' after 4.77 s
[11:37:41] Finished 'copy' after 4.77 s
[11:37:41] Finished 'pages' after 4.79 s
[11:37:42] Finished 'images' after 5.78 s
[11:37:42] Finished 'javascript' after 6.45 s
[11:37:42] Starting 'styleGuide'...
[11:37:42] Finished 'styleGuide' after 31 ms
[11:37:42] Finished 'build' after 6.51 s
[11:37:42] Starting 'server'...
[11:37:42] Finished 'server' after 44 ms
[11:37:42] Starting 'watch'...
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:8000
    External: http://192.168.1.72:8000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.72:3001
 -------------------------------------
[BS] Serving files from: dist
```

Based on the code and the path strings, I can't see how gulp-html-i18n could do anything other than misbehave and spit out those funky path strings. Here are the values of the relevant variables I see in the debugger when hitting the breakpoint at line 305 in index.js for the first time:

newFilePath: "c:\Coalesense-Website\Coalesense\src\pages\index.html"
file.base: "c:\Coalesense-Website\Coalesense\src\pages"
lang: de

Just the fact that line 305 directly concatenates 'file.base' and 'lang' without a separator is obviously incorrect, so if this code works for other people, the path strings must already be wrong. If you setup the Foundation project as I mentioned above, what does through2 log in your environment?

**Comment by dominicscimeca** [comment]
Just redid it. Exactly the same.

```
function pages() {
  return gulp.src('src/pages/**/*.{html,hbs,handlebars}')
    .pipe(panini({
      root: 'src/pages/',
      layouts: 'src/layouts/',
      partials: 'src/partials/',
      data: 'src/data/',
      helpers: 'src/helpers/'
    }))
    .pipe(i18n({
      langDir: 'src/languages',
      delimiters: ['{${', '}$}'],
      createLangDirs: true,
      trace: true
    }))
    .pipe(gulp.dest(PATHS.dist));
}
```
works just fine. what does you language folder look like?

mine is : 
```
languages
     de
         index.json
     en
         index.json
```

**Comment by andreas-henning** [comment]
>what does you language folder look like?

Just like yours.

What does through2 log to the console with your current setup? If I knew what the paths were supposed to look like for everything to work as expected I could maybe start digging deeper on my end.

**Comment by dominicscimeca** [comment]
```
before path C:\Users\User\projects\zurb\src\pages\index.html
before base C:\Users\User\projects\zurb\src\pages\
after path C:\Users\User\projects\zurb\src\pages\de/index.html
after base C:\Users\User\projects\zurb\src\pages\
after path C:\Users\User\projects\zurb\src\pages\en/index.html
after base C:\Users\User\projects\zurb\src\pages\
```

Here is a git repo of what i did. Pull it down and see if it works for you. And if so, see the different between what you have and what it does.

https://github.com/dominicscimeca/windows-gulp-html-i18n-test

i am using `foundation watch` to do the run and build the files

**Comment by andreas-henning** [comment]
Thx. I'll take a look at that tomorrow. G'night!

**Comment by andreas-henning** [comment]
Yup. Your 'windows-gulp-html-i18n-test' works just fine for me too! However, the issue is unrelated to any of our files. The culprit was an outdated package.

At least gulp-load-plugins and browser-sync were one version behind. Possibly also gulp itself (didn't get a good look before I prematurely closed the window...sorry). I pulled down the latest versions of all npm packages into my project and gulp-html-i18n now works fine (without modification).  Still, gulp-html-i18n is not entirely innocent in this (IMHO).

By comparing our traces from through2 we can identify what caused gulp-html-i18n to fail on me:

your trace:
```
before path C:\Users\User\projects\zurb\src\pages\index.html
before base C:\Users\User\projects\zurb\src\pages\   <-- with trialing '\'
```
my trace:
```
before path C:\Coalesense-Website\Coalesense\src\pages\index.html
before base C:\Coalesense-Website\Coalesense\src\pages   <-- without trialing '\'
```

It's the trailing '\'.  Without it gulp-html-i18n misbehaves in the way I experienced. The misbehavior can be simulated by removing the trailing '\' in the debugger, or by using the wrong combination of packages which causes them to pass a path parameter to gulp-html-i18n which it can't deal with (unfortunately I can't tell you what that combination was).

Since gulp-html-i18n's path manipulations fail without the trailing '\', I'd recommend it validate its input parameters and append the trailing '\' if it's missing. It wouldn't have failed on me if it did that. ;-)

I'd appreciate input paths being validated, but in general I'd say this is sorted for me now. Thanks for your time Dominic!

**Comment by webyom** [comment]
@andreas-henning I have published a new version containing the fix of this issue from @dominicscimeca . Please have a try.

**Comment by dominicscimeca** [comment]
@webyom :  I think @andreas-henning is saying it was already fixed by updating the dependencies he was using. 

> The culprit was an outdated package.
> 
> At least gulp-load-plugins and browser-sync were one version behind. Possibly also gulp itself (didn't get a good look before I prematurely closed the window...sorry). I pulled down the latest versions of all npm packages into my project and gulp-html-i18n now works fine (without modification).

And

> Either way I'd say this is sorted for me now though.

**Comment by andreas-henning** [comment]
@webyom, @dominicscimeca

Yes, dominicscimeca is right. The issue went away after updating my local npm dependencies.

I just updated all my local npm dependencies again, including gulp-html-i18n (0.6.4). It  doesn't seem to contain this patch.

So, I copy/pasted this change to my local source files. I then reproduced my error by removing the trailing "/" from the path.base variable in the debugger. I can confirm this would have fixed the issue.

Will this be pushed to the npm repository soon?

**Comment by andreas-henning** [comment]
@webyom, @dominicscimeca

I've never written a line of JS code in my life, so I don't deserve to have an opinion on any of this, but I do wonder if the differences between Windows and Unix path separators may be the source of your problems. For example, at the point where I copied this patch into the index.js file, in my project the debugger shows me this:

path.base: "c:\\Coalesense-Website\\Build\\src\\pages\\"

This path uses escaped Windows path separators. It is a correct and valid path as it uses has a trailing separator. However, you assume the use of Unix or Mac path separators. You check for a trailing "/" which doesn't exist, so you add it which results in this:

path.base: "c:\\Coalesense-Website\\Build\\src\\pages\\**/**"

That is a rather funky path. That path does get cleaned up later on, but until it gets cleaned up it's an invalid path. Any code that attempts to manipulate paths before it is cleaned up could potentially fall on its face and result in a bug.

Could this sort of thing be what is causing problems?

**Comment by andreas-henning** [comment]
@webyom, @dominicscimeca

Yes, dominicscimeca is right. The issue went away after updating my local npm dependencies.

I can confirm that this patch would have fixed my issue, but as mentioned by @mjanos it also brakes gulp plugins that are further down the pipe, like browser_sync.

The problem is that the patch assumes the use of Mac/Unix path separators which are different from what is used on Windows. This is a "quick and dirty" modification to the patch that solves the browser sync issue:

```
      if (file.base && (file.base.slice(-1) !== '/') && (file.base.slice(-1) !== '\\')) {
        file.base += '/';
      }
```

Based on @mjanos10 comments in regard to #22, it sounds like his path problem was also a result of some combination of packages impacting path handling rather than a direct result of this patch.

So where do we stand with this now?

**Comment by webyom** [comment]
@andreas-henning thanks for your investigation. I also suspected that this issue was root in lack of consideration for the OS path separator. Since upgrading dependencies can resolve this issue, I think this fix is unnecessary. How do you think :)

**Comment by andreas-henning** [comment]
Hey @webyom. I respectfully disagree. In my view all input parameters (in this case the path) to a public method must be validated and ensured that they comply to your assumptions and expectations. Always. As I understand it (I could be wrong), you receive the path from the plugin that precedes gulp-html-i18n
in the asset pipeline. You can't make assumptions about how that path will be formatted (type of separator, whether it has a trailing separator, or if the path even exists). As it is now, and as I understand it, any update to the preceding plugin has the potential to break gulp-html-i18n on Windows (because you assume Linux/Mac separators). Even just rearranging the order of the plugins in the asset pipeline could break  gulp-html-i18n on Windows. I don't think that's reliable/stable enough. I've spent enough time with your plugin so that I'm perfectly fine with whatever you do. Should something similar pop up again I can do a local fix myself. However, since we can't control how every other plugin works, I'd expect for this issue to occasionally pop up on Windows if it is not fixed. It's up to you.  ;-)

**Comment by webyom** [comment]
@andreas-henning agree with you. 0.6.5 fix this issue. If you still see any issue with windows platform, and have any solution, please don't hesitate to send PR :)

**Comment by andreas-henning** [comment]
Downloaded and tested it. Looks very good to me now. As long as the patch isn't entirely removed again, I'd say it's safe to close this issue. Many thanks! ;-)

If I find anything in the future I'll consider a PR ;-)
