### ISSUE TITLE
Wrong filename after render

### ISSUE THREAD

**Issue by mjanos10** [webyom/gulp-html-i18n#22]
Hi!

I can't seem to find out why but the output html files have an `ndex.html` name (instead of `index.html`).

**Project structure:**
```
|──public
   ├──hu
      ├──ndex.html
   ├──en
      ├──ndex.html
├──source
   ├──html
       ├──index.html
   ├──lang
      ├──hu
         ├──index.yaml
      ├──en
         ├──index.yaml
├──gulpfile.js
```
**gulpfile.js**
```
/*...*/
gulp.task( 'html', () => {
	return gulp.src( 'source/html/*.html' )
		.pipe(i18n({
			langDir: 'source/lang',
			createLangDirs: true,
			defaultLang: 'hu',
			renderEngine: 'mustache'
		}))
		.pipe(gulp.dest('public'))
		.pipe( browserSync.reload( {
			stream: true,
			once: true
		} ) );
} )
/*...*/
```

I'm working on Windows now btw.

Also if it's not a big problem, it would be awesome if you could tell me why browser-sync does not show me the generated file? I have to save on it twice to see the effect.
Thanks!

**Comment by webyom** [comment]
@dominicscimeca I think this bug is related to the fix for #20. Since #20 is caused by outdated package, I decide to rollback the fix for #20.

**Comment by dominicscimeca** [comment]
@webyom Maybe so. First, please @mjanos10 update all of your packages to see if that is the issues. Then if that doesn't work please let me know if this new version fixes the issue. 

Thanks :)

**Comment by mjanos10** [comment]
Thanks for the quick response. I have updated all my packages and now everything works as expected, even the browsersync problem is fixed now :) Thanks again !
