### ISSUE TITLE
Preprocess the JavaScript input

### ISSUE THREAD

**Issue by s1n** [webyom/gulp-html-i18n#24]
I'm trying to use this in conjunction with Pug however I cannot nest Pug strings within the JSON format because I have to process the pug files to HTML in the gulp stream first. That is, I pass the pug files through to generate the HTML, but the i18n strings might be pug strings as well (eg some words within a sentence might need to be bold and I would rather do that with Pug as well).

Can I use the JavaScript form instead to try to process the strings through Pug before this module does a replacement? Is there another way

**Comment by webyom** [comment]
> but the i18n strings might be pug strings as well (eg some words within a sentence might need to be bold and I would rather do that with Pug as well)

@s1n could you post your pug code to let me have a look

**Comment by s1n** [comment]
Sorry for the late response.

Here is what I have:
https://github.com/s1n/xwingcodex/blob/master/app/layouts/layout.pug#L80
https://github.com/s1n/xwingcodex/blob/master/lang/en/layout.json#L12

Here is my gulp script:
https://github.com/s1n/xwingcodex/blob/master/gulpfile.js#L108-L120

Basically, I want to run the strings in the JSON local file through pug as well. I'm not sure if this is the right plugin for this approach, if there is a more appropriate plugin, or if I am doing things incorrectly.

**Comment by s1n** [comment]
Note that I just found out about [gulp-data](https://github.com/colynb/gulp-data) and I'm not sure if that's a more correct approach or not.

**Comment by webyom** [comment]
@s1n I think you can exchange the sequence of these two process, first do i18n, then pug. Please have a try.

**Comment by s1n** [comment]
Actually, I was able to get this to work on the pug files directly (strangely) but I'm struggling with the filenames it generates with createLangDirs.

What I have is this: ./app/section/page.pug
What I get is this: ./dist/en/page.pug
What I want is this: dist/en/section/page.pug

Currently, I am working to move the files after they are generated but I would like to change the path somehow.
