### ISSUE TITLE
Use of variables in language

### ISSUE THREAD

**Issue by NielsvanDijk** [webyom/gulp-html-i18n#25]
Hi is it posible to add variables to the content? like this?

code
``` html
<mj-text align="center" mj-class="padding title sans">
   _(example.title {{email}})
</mj-text>
```

json
``` json
{
    "title": "HIA demo pagina! %{email}",
}
```

**Comment by webyom** [comment]
Sorry for late reply. This tool is for static language resource replacement, and your requirement is for dynamic data rendering. So I don't think there is any chance to support this feature.

**Comment by NielsvanDijk** [comment]
Okay, thanks! i solved it by using 2 strings!!
