### ISSUE TITLE
TypeError: $.i18n is not a function gulp+ fileinclude + browsersync

### ISSUE THREAD

**Issue by EryouHao** [webyom/gulp-html-i18n#28]
when first run the fileinclude + gulp-html-i18n is well, but change html and run fileinclude + gulp-html-i18n is not work.

**Comment by webyom** [comment]
@EryouHao sorry, have no idea what problem you have met. Could you show your code to explain?

**Comment by EryouHao** [comment]
``` javascript
const $ = gulpLoadPlugins({
  rename: {
    'gulp-file-include': 'fileinclude',
    'gulp-html-i18n': 'i18n'
  }
});

gulp.task('fileinclude', () => {
  return gulp.src('app/views/**/*.html')
    .pipe($.fileinclude({
      prefix: '@@',
      basepath: '@file'
    }))
    .pipe($.i18n({
      langDir: 'app/lang',
      trace: true,
      createLangDirs: true,
    }))
    .pipe(gulp.dest('.tmp'));
});
```
 I run task: gulp server,  it will be ok, but watch html change and run task it will be bad.so I must restart gulp server.

I see you from china, can you help pass add friend with me?

WeChat: heyqiuxiaobei
QQ: 846475472

thank you!

**Comment by EryouHao** [comment]
it's gulp-load-plugins's lazy loading
