### ISSUE TITLE
Request: Current filename markup ${{ _filename_ }}

### ISSUE THREAD

**Issue by FranciscoKnebel** [webyom/gulp-html-i18n#31]
In the same way you can use `${{ _lang_ }}$`, `${{ _langs_ }}$`, and `${{ _default_lang_ }}$`, it would be useful if you could obtain the **name for the file you are currently modifying** as a special markup.

That way, one could, for instance, create a link to `${{ _lang_ }}/${ _filename_ }`, which would render differently for each page, according to current language and current file.

PS: would also be useful if you could use each value from langs individually, so you could loop through languages. That way, you can refer to langs[x]/filename, and create links to that file in all languages.
It's interesting, but another big feature for another issue.

**Comment by FranciscoKnebel** [comment]
The use case I found for this is the need to swap to another language, but still remain on the current page.

**Comment by webyom** [comment]
Added `_filename_` and `_filepath_` in version `0.9.0`

**Comment by FranciscoKnebel** [comment]
Thank you @webyom :+1:
