### ISSUE TITLE
Fallback language doesn't work with langRegExp

### ISSUE THREAD

**Issue by abiaskosty** [webyom/gulp-html-i18n#34]
Hi, first of all thanks for this helpful tool!

I found a bug which is reproduced with following config:
```
{
  langRegExp: /\[\[ ?([\w-.]+) ?\]\]/g,
  fallback: 'es'
}
```
As you see I'm using a pattern `[[ propName ]]`. But instead of using a property from fallback language it will put `${{ propName }}`. 

The bug is in this line https://github.com/webyom/gulp-html-i18n/blob/master/src/index.coffee#L77.

**Comment by webyom** [comment]
@abiaskosty have published 0.10.1 for this fix. Thanks a lot.
