### ISSUE TITLE
Having problems with 'createLangDirs'

### ISSUE THREAD

**Issue by mertakdut** [webyom/gulp-html-i18n#36]
Hello,

I couldn't get the _createLangDirs_ parameter to work as expected. Could you please check if I am doing something wrong?

```
gulp.task('pug', function () {
  return gulp
    .src(['src/views/*.pug', 'src/views/blog/*.pug'], {
      base: './src/views/'
    })
    .pipe(pug())
    .pipe(i18n({
		langDir: 'src/locales/'
		createLangDirs: true
	}))
    .pipe(gulp.dest('tmp'))
});
```

I set the base directory to have the blog folder in a separate folder in _tmp_.
Everything works as expected until _createLangDirs_ parameter is set. It creates two folders with weird paths:

> viewsen/path/to/project/src/views
> viewstr/path/to/project/src/views

My json files are located in _src/locales/en_ and _src/locales/tr_ folders.

Thanks in advance.

**Comment by mertakdut** [comment]
Separated the i18n task from the pug task. Now the problem is clearer.

```
gulp.task('i18n', function () {
  return gulp.src('tmp/blog/*.html')
    .pipe(i18n({
      createLangDirs: true,
      langDir: 'src/locales'
    }))
    .pipe(gulp.dest('tmp/blog'));
});
```

It gets the html files from the source directory and copy them into _tmp_ folder. Folders are named _blogen_ and _blogtr_.

Instead of putting path separator between the blog and tr, it concats them into eachother.

The path where html files reside should have been _tmp/blog/en/_, but folder created in _tmp_ folder is named _blogen_.

**Comment by mertakdut** [comment]
I was able to work it around by changing line 335 with this line:
```
var newFileBase = file.base + path.sep;
```

And line 337 with this line:
```
newFilePath = newFileBase + lang + path.sep + newFilePath.slice(newFileBase.length);
```

As I've seen in my debug sessions, it wasn't able to append path.sep to file.base.

Let me know if I am doing something wrong. Thanks in advance.

**Comment by webyom** [comment]
I think it's a confliction with base option of gulp.src method. I have changed the code as not changing the file base. Please update and have a try.

**Comment by mertakdut** [comment]
The problem in my first comment persists. With a little change on paths.

> tmp/en/path/to/project/src/views
> tmp/tr/path/to/project/src/views

But the problem I mentioned in my 2nd comment is fixed. Running i18n task as a separate task with a separate src has no issue. As you stated, it must be the confliction with base option.

**Comment by webyom** [comment]
It's caused by relative base path. I have fixed it and updated test case, please try again.

**Comment by mertakdut** [comment]
Fixed.
