### ISSUE TITLE
Add option to hide `not found in definition file!` messages

### ISSUE THREAD

**Issue by WilliamMayor** [webyom/gulp-html-i18n#38]
I've got two locales that are very similar, en-gb and en-ie. en-gb is the fallback locale, so in en-ie I can miss out most of the translations and use the fallback. This results in lots of red error messages.

Could we add an option to ignore these errors if there's a fallback?

Thanks!

**Comment by webyom** [comment]
I just removed the annoying error. Please update to 0.12.0

**Comment by WilliamMayor** [comment]
That's perfect! Thanks!
