### ISSUE TITLE
Fallback option doesn't work with mustache engine

### ISSUE THREAD

**Issue by igodorogea** [webyom/gulp-html-i18n#39]
Fallback option works only with default engine "regex", it doesn't with "mustache" engine.

**Comment by igodorogea** [comment]
Yes, I also checked, mustache doesn't support any fallback mechanism.
I've tried to overcome this limitation here https://github.com/igodorogea/gulp-html-i18n/commit/75e4b3968eab17ea3bd224dd9daa8530544bb2de.
Please let me know what you think.

**Comment by webyom** [comment]
@igodorogea good, please send PR.
