### ISSUE TITLE
NPM out of date

### ISSUE THREAD

**Issue by peteorpeter** [webyom/gulp-html-i18n#4]
Hi!  I noticed that the version published on NPM (0.1.1) is quite a bit behind the github repo's (0.2.3).  
This threw me off because the github documentation is out-of-synch with the npm code.  It also give the (false!) impression that the module is buggy or poorly documented.

Thanks for the project!

**Comment by webyom** [comment]
@peteorpeter thanks for your feedback. I have published the newest version(0.2.3) to npm, sorry for the inconvenience.
