### ISSUE TITLE
Solve langDir with different Paths.

### ISSUE THREAD

**Issue by andresclua** [webyom/gulp-html-i18n#42]
Hello!
I have the following problem.
I have a working version in which I have 3 languages: English, Spanish and French.

The structure is index.html, and English is the default language. For the others, the URL would be /es/index.html and /fr/index.html. 

The problem I'm facing is that the path from assets are not working on my end. All assets and css files are working properly only with the default index.html page. But when I load the other languages, they are not working, since they are inside a different folder. I'm attaching some screenshots so it's more clear. 

Do you know what I can do?
<img width="431" alt="Captura de Pantalla 2019-11-18 a la(s) 18 33 09" src="https://user-images.githubusercontent.com/612806/69075604-fd71f280-0a31-11ea-9004-35ece6be9b89.png">

Thanks in advance!

**Comment by webyom** [comment]
You may resolve the relative path to cdn path first.
FYI https://www.npmjs.com/package/gulp-prefix
