### ISSUE TITLE
Object keys with `.` values.

### ISSUE THREAD

**Issue by crswll** [webyom/gulp-html-i18n#46]
Helllo!

We'd like to do:

```json
{
  "foo.bar.baz": "Hello Wolrd",
}
```

Instead of

```json
{
  "foo": {
    "bar": {
      "baz": "Hello World"
    },
  }
}
```
Can we accomplish this? Would a PR for this be welcomed? Is there an option I'm missing?

We started out liking the nesting but have quickly grown to not like it. We would like to keep  using`{{$ dictionary.foo.bars.baz $}}` though.

**Comment by webyom** [comment]
@crswll is there any reason for choosing "foo.bar.baz" over "foo_bar_baz" or "foo-bar-baz" for the key?

**Comment by crswll** [comment]
Nothing serious besides a massive PR. We do use hyphens already so we’d need something like `foo_bar-baz_buzz` most likely. I’d say it’s strictly aesthetic which is a pretty bad reason. I’ll run it by the team.

**Comment by crswll** [comment]
I guess the `.`, even though we aren’t in JS really at that point, still denotes kind of like a child I guess? Probably over thinking it.

**Comment by crswll** [comment]
Thanks @webyom! I'm just going to close it. Likely not worth the discussion haha.
