### ISSUE TITLE
The document confused me

### ISSUE THREAD

**Issue by twxia** [webyom/gulp-html-i18n#8]
Hi ~ This plugin is awesome. Thanks~

If README can write more clearly will be more friendly :smile:
(like: method about `index.src.html` description, example)

* `defaultLang` will translate the default language's `index.html` and others will create their language's folder and `index.html`. If this can have a options also create the `defaultLang` folder

like below structure, I want to use it with browserSync to live edit:
```
gulp.task('localize', function() {
  var dest  = 'app';
  var index = 'app/template/index.src.html';

  return gulp.src(index)
    .pipe(i18n({
      langDir: 'app/langs',
      createLangDirs: true,
      defaultLang: 'en-us'
    }))
    .pipe(gulp.dest(dest))
    .pipe(browserSync.reload({stream: true}));
});
```
![screenshot from 2016-04-09 22 52 19](https://cloud.githubusercontent.com/assets/2068895/14404343/bf672032-fea5-11e5-9b64-91e119182d65.png)

BTW Is `.src.html` same as a template concept ? like I use it now

**Comment by webyom** [comment]
@twxia thanks for your feedback. I have updated the code, and now it will generate a language dir even for `defaultLang`. As I'm not a native english speaker, there may be some mistakes in the document. If you can make it clearer, please give me a hand. 😄
